name: Build
        
on:
  push:
    branches:
      - main
  pull_request: {}


jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node.js
        uses: actions/setup-node@v3
      - name: install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Gravity
        run: npx gravityci '.svelte-kit/output/**/*'
        env:
            GRAVITY_TOKEN: ${{ secrets.GRAVITY_TOKEN }}
            GRAVITY_HOST: ${{ vars.GRAVITY_HOST }}
          
